name: flutter_file_preview
description: PDF, Word, Excel, and PowerPoint Viewer For Flutter App.
version: 0.0.1
author: wenjunhuang<kongkonghwj@gmail.com>
homepage: https://github.com/aliyoge/flutter_file_preview

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: zzaning.com.flutter_file_preview
        pluginClass: FlutterFilePreviewPlugin
      ios:
        pluginClass: FlutterFilePreviewPlugin

#      web:
#        pluginClass: FilePreviewPlugin
#        fileName: xxxx_web.dart
#      linux:
#        pluginClass: FilePreviewPlugin